"""Fast, memory-conscious RDS data.frame reader for Python."""

from ._core import (
    InvalidRDS,
    RDSCatalogError,
    RDSError,
    RDSLimitError,
    ReaderLimits,
    UnsupportedRDS,
)
from ._write import RDSWriteError, write_rds
from .api import (
    ParquetTable,
    RDSCatalog,
    RDSColumnInfo,
    RDSDataset,
    RDSInspection,
    RFileInfo,
    RTableInfo,
    compiled_backend_available,
    convert_rds,
    extract_rds_tables,
    inspect_r_file,
    inspect_rds,
    list_rds_tables,
    materialize_uncompressed,
    open_rds,
    read_r_object,
    read_rds,
    read_rds_arrow,
    read_rds_dataframe,
    read_rds_duckdb,
    read_rds_polars,
    to_parquet,
)

__all__ = [
    "InvalidRDS",
    "ParquetTable",
    "RDSCatalog",
    "RDSCatalogError",
    "RDSColumnInfo",
    "RDSDataset",
    "RDSError",
    "RDSInspection",
    "RDSLimitError",
    "RDSWriteError",
    "RFileInfo",
    "RTableInfo",
    "ReaderLimits",
    "UnsupportedRDS",
    "compiled_backend_available",
    "convert_rds",
    "extract_rds_tables",
    "inspect_r_file",
    "inspect_rds",
    "list_rds_tables",
    "materialize_uncompressed",
    "open_rds",
    "read_r_object",
    "read_rds",
    "read_rds_arrow",
    "read_rds_dataframe",
    "read_rds_duckdb",
    "read_rds_polars",
    "to_parquet",
    "write_rds",
]

__version__ = "0.4.0b2"
