"""Fast, memory-conscious RDS data.frame reader for Python."""

from ._audit import (
    RDSDiffEntry,
    RDSDiffReport,
    RDSValidationIssue,
    RDSValidationReport,
    diff_rds,
    validate_rds,
)
from ._core import (
    InvalidRDS,
    RDSCatalogError,
    RDSError,
    RDSLimitError,
    ReaderLimits,
    UnsupportedRDS,
)
from ._dataset import RDSCollection, open_rds_dataset
from ._write import RDSWriteError, write_rds
from .api import (
    ParquetTable,
    RDSCatalog,
    RDSColumnInfo,
    RDSDataset,
    RDSInspection,
    RFileInfo,
    RTableInfo,
    compiled_backend_available,
    convert_rds,
    extract_rds_tables,
    inspect_r_file,
    inspect_rds,
    list_rds_tables,
    materialize_uncompressed,
    open_rds,
    read_r_object,
    read_rdata,
    read_rds,
    read_rds_arrow,
    read_rds_dataframe,
    read_rds_duckdb,
    read_rds_polars,
    to_parquet,
)

__all__ = [
    "InvalidRDS",
    "ParquetTable",
    "RDSCatalog",
    "RDSCatalogError",
    "RDSCollection",
    "RDSColumnInfo",
    "RDSDataset",
    "RDSDiffEntry",
    "RDSDiffReport",
    "RDSError",
    "RDSInspection",
    "RDSLimitError",
    "RDSValidationIssue",
    "RDSValidationReport",
    "RDSWriteError",
    "RFileInfo",
    "RTableInfo",
    "ReaderLimits",
    "UnsupportedRDS",
    "compiled_backend_available",
    "convert_rds",
    "diff_rds",
    "extract_rds_tables",
    "inspect_r_file",
    "inspect_rds",
    "list_rds_tables",
    "materialize_uncompressed",
    "open_rds",
    "open_rds_dataset",
    "read_r_object",
    "read_rdata",
    "read_rds",
    "read_rds_arrow",
    "read_rds_dataframe",
    "read_rds_duckdb",
    "read_rds_polars",
    "to_parquet",
    "validate_rds",
    "write_rds",
]

__version__ = "0.4.0b3.dev0"
